### ISSUE TITLE
Error using convertAudio

### ISSUE THREAD

**Issue by gzcarlos** [RogelioLB/node-yt-converter#1]
I'm new with this library, so just used this 

`
var yt = require('yt-converter');
var path = require('path');

var url = 'https://www.youtube.com/watch?v=4CAgg2qmaAY';

yt.convertAudio(url,140, path.join(__dirname), function(a){
    console.log('CLOSE', a);
});
`

And I'm getting this error:

`
app_path\node_modules\ytdl-core\lib\url-utils.js:75
exports.validateID = id => idRegex.test(id.trim());
                                           ^

TypeError: Cannot read properties of undefined (reading 'trim')
    at Object.exports.validateID (app_path\node_modules\ytdl-core\lib\url-utils.js:75:44)
    at Object.exports.getVideoID (app_path\node_modules\ytdl-core\lib\url-utils.js:58:15)
    at Function.exports.<computed> [as getInfo] (app_path\node_modules\ytdl-core\lib\info.js:484:29)
    at app_path\node_modules\yt-converter\src\utils\getInfo.js:42:14
    at new Promise (<anonymous>)
    at getInfo (app_path\node_modules\yt-converter\src\utils\getInfo.js:40:26)
    at Object.convertAudio (app_path\node_modules\yt-converter\src\utils\convertAudio.js:41:28)     
    at Object.<anonymous> (app_path\index3.js:37:4)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
`

Any clue on what is wrong?

**Comment by RogelioLB** [comment]
Sorry, first of all i change the way of how to introduce the params, now you have to do it in a object like this,
````js
const yt = require("yt-converter")


yt.convertAudio({
    url: "https://www.youtube.com/watch?v=JzbGrvkqV5w",
    itag: 140,
    directoryDownload: __dirname
})
```
thanks for your support i'll update the docs

**Comment by RogelioLB** [comment]
I alredy change the docs, hopefully you can use it!
